#!/bin/bash

servers=$(vim --serverlist)
servcount=$(vim --serverlist|wc -l)

if test -n $VIM_SERVER
then
    if [[  $servers =~ $VIM_SERVER ]]
    then
        vim --servername $VIM_SERVER --remote-tab-silent "$@"
    else
        vim --servername $VIM_SERVER -p "$@"
    fi
elif (( $servcount > 0 ))
then
    target=$(vim --serverlist|head -n 1)
    vim --servername $target --remote-tab-silent "$@"
else 
    vim -p "$@"
fi
